<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace DS\Digest\Bundle\DigestBundle\GraphQL;

use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\AddMaterialField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Query\MaterialListField;
use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;

/**
 * Class Schema
 * @package DS\Digest\Bundle\DigestBundle\GraphQL
 */
class Schema extends AbstractSchema
{
    /** {@inheritdoc} */
    public function build(SchemaConfig $config)
    {
        $config->getQuery()->addFields([
            'materialList' => new MaterialListField(),
        ]);

        $config->getMutation()->addFields([
            'addMaterial' => new AddMaterialField(),
        ]);
    }
}
