<?php
/**
 * This class was automatically generated by GraphQL Schema generator
 */

namespace DS\Digest\Bundle\DigestBundle\GraphQL;

use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\AddMaterialField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\AddMaterialToDigestField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\CreateDigestField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\RemoveMaterialFromDigestField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\RenameDigestField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Mutation\UpdateMaterialField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Query\DigestField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Query\DigestListField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Query\MaterialField;
use DS\Digest\Bundle\DigestBundle\GraphQL\Query\MaterialListField;
use Youshido\GraphQL\Schema\AbstractSchema;
use Youshido\GraphQL\Config\Schema\SchemaConfig;

/**
 * Class Schema
 * @package DS\Digest\Bundle\DigestBundle\GraphQL
 */
class Schema extends AbstractSchema
{
    /** {@inheritdoc} */
    public function build(SchemaConfig $config)
    {
        $config->getQuery()->addFields([
            'material' => new MaterialField(),
            'materialList' => new MaterialListField(),
            'digestList' => new DigestListField(),
            'digest' => new DigestField(),
        ]);

        $config->getMutation()->addFields([
            'addMaterial' => new AddMaterialField(),
            'updateMaterial' => new UpdateMaterialField(),
            'createDigest' => new CreateDigestField(),
            'renameDigest' => new RenameDigestField(),
            'addMaterialToDigest' => new AddMaterialToDigestField(),
            'removeMaterialFromDigest' => new RemoveMaterialFromDigestField(),
        ]);
    }
}
