version: '3.3'
services:
    nginx:
        image: nginx:1.12
        depends_on:
            - digest
            - node
        ports:
            - 80:80
        volumes:
            - ./:/var/www/digest
            - ./docker/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
        restart: always
        environment:
            VIRTUAL_HOST: digest.stampany.com

    digest:
        image: registry.stampany.com/dario_swain/digest:latest
        depends_on:
            - mongo
        restart: always
        volumes:
            - ./:/var/www/digest
        environment:
            MONGO_SERVER: 'mongodb://mongo:27017'
            MONGO_DB: 'digest'
            SECRET: '4b38b8b708f77d8b8c9bbb08b3bc655539af15b6'
            SYMFONY_ENV: 'dev'
            SYMFONY_DEBUG: 'true'

    mongo:
        image: mongo:3.2
        restart: always

    node:
        image: teracy/angular-cli:latest
        restart: always
        command: /bin/bash -c "npm install && ng serve --host=0.0.0.0 --port 80 --disable-host-check"
        working_dir: /app/src-web
        volumes:
            - ./:/app
