DS\Digest\Domain\Digest\Model\Material:
    type: document
    fields:
        id:
            id: true
            type: string
            strategy: NONE
        title:
            type: string
        description:
            type: string
        url:
            type: string
        proposedBy:
            type: string
        language:
            type: string
        tags:
            type: collection
        createdAt:
            type: date
